apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "services-api.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "services-api.standard-labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
{{ include "services-api.standard-selector-labels" . | indent 6 }}
  template:
    metadata:
      labels:
{{ include "services-api.standard-labels" . | indent 8 }}
    spec:
      containers:
        - name: {{ include "services-api.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /status/probes/liveness
              port: http
          readinessProbe:
            httpGet:
              path: /status/probes/readiness
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: NODE_ENV
              value: {{ .Values.configuration.nodeEnv | quote }}
            - name: SERVICES_API_PORT
              value: {{ .Values.configuration.applicationPort | quote }}
            - name: SERVICES_DB_HOST
              value: {{ .Values.database.host | quote }}
            - name: SERVICES_DB_USER
              value: {{ .Values.database.user | quote }}
            - name: SERVICES_DB_PASSWORD
              value: {{ .Values.database.password | quote }}
            - name: SERVICES_DB_NAME
              value: {{ .Values.database.name | quote }}
